### ISSUE TITLE
address: script compiled on Linux wants bash on Windows

### ISSUE THREAD

**Issue by rvjansen** [RexxLA/NetRexx#38]
as in the title, found this out while something at work was demonstrated.

**Comment by remesm** [comment]
Hi René,
good catch, too bad for the demo.
I've pushed a fix to move resolving SYSTEM from compile time to runtime.
Marc

**Comment by rvjansen** [comment]
Thanks for fixing it! First time I encountered it actually, will make sure 4.05 is out early.
