### ISSUE TITLE
Startup scan should avoid '.\AppData\Local\Application Data' directory on MS Windows.

### ISSUE THREAD

**Issue by rvjansen** [RexxLA/NetRexx#47]
For users working from their home directory, mentioned directory causes trouble and should be special-cased like the Apple Siri directory.

**Comment by remesm** [comment]
Already fixed in 4.05 with commit e99033e110e5364cbbc6812cef530a587c79adb7 when reverting back to File instead of Path.

**Comment by remesm** [comment]
I suspect LinkOption.NOFOLLOW_LINKS the culprit of the 4.04 'Path' way traversing the directory tree..

**Comment by remesm** [comment]
can be closed. Fixed
