### ISSUE TITLE
4.06: pipelines specs fs issue

### ISSUE THREAD

**Issue by rvjansen** [RexxLA/NetRexx#57]
Jeff Henry:
```
C:\NetRexx>pipe "literal a-b-c-d | spec fs - f3 1 f1 n f2 n | cons"
cEEab
```
Where did the 'EE' come from? I've tried with other field separator characters but get the same result. I'm running NetRexx 4.06 on Windows 11.
BTW, the same pipe works as I would expect on CMS Pipes (on the z/VM 7.2 system at work):
```
pipe literal a-b-c-d | spec fs - f3 1 f1 n f2 n | cons  
cab                                                      
Ready; T=0.01/0.01 11:12:12                             
```

**Comment by remesm** [comment]
Fixed with commit f23876
https://sourceforge.net/p/netrexx/code/ci/f2387603fef9c3129274bc827826c623f0c6ca50/
